#!/bin/bash

USER=user
PASS=pass

do_start() {
  while true ; do
    IP=$(ifconfig eth0 | grep inet\ )
    [ -z "$IP" ] && 
      (
        ifconfig eth0 up && dhclient eth0 2&>/dev/null 
      )
    sleep 10
    C=$(curl -I google.com 2>/dev/null | grep google.com)
    [ -z "$C" ] &&
      (
        curl -k "http://securelogin.arubanetworks.com/cgi-bin/login" \
             -d "user=$USER&fqdn=insa-lyon.fr&password=$PASS" 2&>/dev/null
      )
  done &
}

do_stop() {
	killall autoconnect
}

case "$1" in
    start|restart|reload)
        do_start
    ;;
    stop)
        do_stop
    ;;
    *)
        echo "Script only started at boot for system configuration."
    ;;
esac

exit 0

